import watches from '../../Assets/watches.jpg';
import shoes from '../../Assets/shoess.jpg';

const products = [
    { id: 1,
      name: 'Nike',
      description: 'shoe1', 
      price: 19.99,
      image: shoes,
    },
    { id: 2, 
      name: 'Puma', 
      description: 'shoe2', 
      price: 19.99,
      image: shoes,
    },
    { id: 3, 
      name: 'Addidas', 
      description: 'shoe3', 
      price: 19.99,
      image: shoes, 
    },
    { id: 4, 
      name: 'Fastract', 
      description: 'watch1', 
      price: 19.99,
      image: watches,
    },
    { id: 5, 
      name: 'Fastract', 
      description: 'watch1', 
      price: 19.99,
      image: watches,
    },
    { id: 6, 
      name: 'Fastract', 
      description: 'watch1', 
      price: 19.99,
      image: watches,
    },
    { id: 7, 
      name: 'Fastract', 
      description: 'watch1', 
      price: 19.99,
      image: watches,
    },
  ];
export default products
